## Creating NumPy Arrays

In [ ]:
# np.array - to create an array
import numpy as np

a = np.array([1,2,3])
print(type(a))
print(a)

<class 'numpy.ndarray'>
[1 2 3]


In [ ]:
# 2D and 3D arrays
b = np.array([[1,2,3],[4,5,6]])
print(b)
print(type(b))

c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# to create an array of a specific data type, float, bool using dtype(datatype)
np.array([1,2,3], dtype=float)
np.array([1,0,1], dtype=bool)
np.array([1,2,3], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [ ]:
# arange function
np.arange(1,11)
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [ ]:
# reshape function
# to change the shape(dimensions) of an array without changing its actual data
# works with both normal arrays and arange
np.arange(1,16).reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [ ]:
# np.ones, np.zeros, np.random
np.ones((3,4))

np.zeros((2,3))

np.random.random((4,5)) # random class -> random method

array([[0.619506  , 0.83096635, 0.81033133, 0.58212662, 0.46206597],
       [0.8513676 , 0.93261386, 0.33388281, 0.66300317, 0.32041056],
       [0.41592466, 0.27587917, 0.9254758 , 0.46495642, 0.81763131],
       [0.23997472, 0.23880951, 0.47171547, 0.8850242 , 0.03909466]])

In [ ]:
# np.linspace(range start, range end, no:of items) - with equal distances between them
# generates linearly seperable points
# default - float,
np.linspace(-5,5,10)
np.linspace(-2,6,20, dtype=int)

array([-2, -2, -2, -1, -1,  0,  0,  0,  1,  1,  2,  2,  3,  3,  3,  4,  4,
        5,  5,  6])

In [ ]:
# np.identity - to make an identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Array Attributes


In [ ]:
a1 = np.arange(10, dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
# ndim - number of dimensions
a3.ndim

3

In [ ]:
# shape - gives the no:of items in every dimension
a3.shape

(2, 2, 2)

In [ ]:
# size - gives the no:of items in the array
a3.size

8

In [ ]:
#itemsize - size of the datatype used
a1.itemsize

4

In [ ]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


## Changing Datatype

In [ ]:
# astype - to change your data type to reduce your memory space consumed
a3.dtype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

## Array Operations

In [ ]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# scaler operations
a2 + 2
a2 - 2
a2 * 2
a2 / 2
a2 % 2

array([[0, 1, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 1]])

In [ ]:
# relational operations
a2 > 15
a2 == 15
a2 != 15

array([[ True,  True,  True, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
# vector operations - works only with those having same shape
a1 + a2
a2 - a1
a1 * a2
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

## Array Functions

In [ ]:
np.random.randint(0,101,size=(3,3))

array([[99, 43, 35],
       [40,  1, 39],
       [75,  7, 56]])

In [ ]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[94., 48., 78.],
       [77., 55., 91.],
       [67., 52., 83.]])

In [ ]:
# max, min, sum, prod
# 0 -> col, 1 -> row
np.max(a1)
np.min(a1)
np.sum(a1)
np.prod(a1)
np.min(a1, axis = 0)
np.max(a1, axis=1)
np.sum(a1, axis=0)

array([238., 155., 252.])

In [ ]:
# mean, median, std, var
np.median(a1)
np.mean(a1, axis=1)
np.var(a1)
np.std(a1)

np.float64(16.041612554021285)

In [ ]:
# trigonometric functions
np.sin(a1)

array([[-0.24525199, -0.76825466,  0.51397846],
       [ 0.99952016, -0.99975517,  0.10598751],
       [-0.85551998,  0.98662759,  0.96836446]])

In [ ]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(13,25).reshape(4,3)
np.dot(a2,a3)

array([[120, 126, 132],
       [400, 422, 444],
       [680, 718, 756]])

In [ ]:
# log and exp
np.log(a1)
np.exp(a1)

array([[6.66317622e+40, 7.01673591e+20, 7.49841700e+33],
       [2.75851345e+33, 7.69478527e+23, 3.31740010e+39],
       [1.25236317e+29, 3.83100800e+22, 1.11286375e+36]])

In [ ]:
# round, floor, ceil
np.round(np.random.random((2,3))*100)
np.floor(np.random.random((2,3))*100)
np.ceil(np.random.random((2,3))*100)

array([[45., 45., 84.],
       [66., 45., 91.]])

## Indexing and slicing

In [ ]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(27).reshape(3,3,3)

a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a1
a1[-1]
a1[0]

np.int64(0)

In [ ]:
a2
a2[1,2]
a2[-2,-2]

np.int64(6)

In [ ]:
a3
a3[1,0,1]
a3[0,1,0]
a3[0,0,0]

np.int64(0)

In [ ]:
a1
a1[2:5] # same as python
a1[2:6:2]

array([2, 4])

In [ ]:
a2
a2[0,:]
a2[:,2]
a2[1:,1:3]
a2[::2,::3]
a2[::2,1::2]
a2[1,::3]
a2[:2,1:]
a2[:2,1::2]

array([[1, 3],
       [5, 7]])

In [ ]:
a3
a3[1]
a3[::2]
a3[0, 1]
a3[1, :,1]
a3[2, 1:, 1:]
a3[::2, 0, ::2]

array([[ 0,  2],
       [18, 20]])

## Iterating

In [ ]:
a1

for i in a1:
  print(i, end = " ")

0 1 2 3 4 5 6 7 8 9 

In [ ]:
a2
for i in a2:
  print(i)
for i in a2:
  for j in i:
    print(j, end = " ")
  print()

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
0 1 2 3 
4 5 6 7 
8 9 10 11 


In [ ]:
a3
for i in a3:
  print(i)
for i in a3:
  for j in i:
    for k in j:
      print(k, end=" ")
    print(end=", ")
  print()

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]
0 1 2 , 3 4 5 , 6 7 8 , 
9 10 11 , 12 13 14 , 15 16 17 , 
18 19 20 , 21 22 23 , 24 25 26 , 
0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 

In [ ]:
# nditer is like getting all elements similar to ravel
for i in np.nditer(a3):
  print(i, end=" ")

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 

## Reshaping

In [ ]:
# transpose
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
# ravel - can convert any dimension array to 1D array
a2.ravel()
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

## Stacking

In [ ]:
# Stacking - only works with same dimension arrays
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

In [ ]:
# horizontal stacking (joins horizontally)
np.hstack((a4,a5))
np.hstack((a4,a5,a4))

array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11]])

In [ ]:
# vertical stacking (joins vertically)
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

## Splitting

In [ ]:
# horizontal splitting (cuts vertically)
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [ ]:
# vertical splitting (cuts horizontally)
np.vsplit(a4,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]